# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74aff8013b417b0482a28ecf92fe89eddc3aff7eb2c8e47bed8b9fcb8f44f7aeb16795f9c36d2dc140af1b96bc3269bb3e4c662c63cdf4ea8ad4f5f06588eccf

test:
  secret_key_base: 2c87ffea5d25bbaea9ce6e986c0051b8886f3f7487c3bda9f8bc269742223e5c0091e94ec10024b682033fe0f7d730b564e7cf101f9a76733101e9f5a25c799f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
